name: Deploy

permissions:
  contents: write

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Install
        run: npm i

      - name: Build
        run: npm run build
        env:
          BASE_PATH: /kyniverse.github.io/

      - name: Create .nojekyll
        run: touch .output/public/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .output/public/